#!/usr/bin/env bash
# Generated by gq (@getquick/site); gq sync rewrites it.
# Makes Polylang's languages match gq.ops.json: wordpress.locale, the default
# language, whose slug is its language code (pt for pt_PT_ao90), then
# wordpress.languages in order. The CMS deploy script (admin.sh) runs it with
# WP-CLI from apps/cms, after setting the site's language and before the
# deploy extensions:
#
#   bash deploy/ploi/polylang.sh pt_PT_ao90 en_US:en
#
# A language Polylang has that gq.ops.json no longer lists stops it, named,
# before it changes anything: it never deletes a language. Otherwise it
# creates each missing language, updates one whose locale or order
# changed, makes the default language Polylang's default, puts each language
# in a URL directory (/en/), the default's hidden, and assigns the content
# that has no language to the default one. Run again, it changes nothing.
set -euo pipefail

default_locale="$1"
shift
default_slug="${default_locale%%_*}"
# Every language as locale:slug, the default first.
languages="$default_locale:$default_slug $*"

# Runs a Polylang command (the PHP below) with WP-CLI:
#   languages             one line per language: slug, locale and order
#   add SLUG LOCALE ORDER, update SLUG LOCALE ORDER
#   settings DEFAULT      the default language and the URL mode
#   assign                content without a language to the default one
polylang() {
  wp eval-file - "$@" <<'PHP'
<?php
if ( ! function_exists( 'PLL' ) || ! PLL() || ! isset( PLL()->model->languages ) ) {
	WP_CLI::error( "Polylang 3.7 or later isn't active: gq.ops.json's wordpress.plugins must list polylang-pro (or polylang)." );
}
$gq_model   = PLL()->model;
$gq_command = array_shift( $args );

// Fails with what went wrong when $result is a WP_Error that holds errors.
$gq_check = static function ( $result, string $failed ): void {
	if ( is_wp_error( $result ) && $result->has_errors() ) {
		WP_CLI::error( $failed . ': ' . implode( ' ', $result->get_error_messages() ) );
	}
};
$gq_language = static function ( string $slug ) use ( $gq_model ): PLL_Language {
	$language = $gq_model->languages->get( $slug );
	if ( ! $language ) {
		WP_CLI::error( "Polylang has no language {$slug}." );
	}
	return $language;
};

switch ( $gq_command ) {
	case 'languages':
		foreach ( $gq_model->languages->get_list() as $gq_lang ) {
			WP_CLI::line( "{$gq_lang->slug} {$gq_lang->locale} {$gq_lang->term_group}" );
		}
		break;
	case 'add':
		list( $gq_slug, $gq_locale, $gq_order ) = $args;
		$gq_check(
			$gq_model->languages->add( array( 'slug' => $gq_slug, 'locale' => $gq_locale, 'term_group' => (int) $gq_order ) ),
			"Could not add the language {$gq_slug} ({$gq_locale}) to Polylang"
		);
		WP_CLI::log( "Added the language {$gq_slug} ({$gq_locale}) to Polylang." );
		break;
	case 'update':
		list( $gq_slug, $gq_locale, $gq_order ) = $args;
		$gq_check(
			$gq_model->languages->update(
				array(
					'lang_id'    => $gq_language( $gq_slug )->term_id,
					'locale'     => $gq_locale,
					'term_group' => (int) $gq_order,
				)
			),
			"Could not update Polylang's language {$gq_slug}"
		);
		WP_CLI::log( "Updated Polylang's language {$gq_slug} ({$gq_locale}, order {$gq_order})." );
		break;
	case 'settings':
		list( $gq_slug ) = $args;
		$gq_language( $gq_slug );
		if ( $gq_model->options->get( 'default_lang' ) !== $gq_slug ) {
			$gq_check( $gq_model->languages->update_default( $gq_slug ), "Could not make {$gq_slug} Polylang's default language" );
			WP_CLI::log( "Made {$gq_slug} Polylang's default language." );
		}
		// The language from the URL's directory (/en/), the default
		// language's hidden, and no /language/ before it.
		foreach ( array( 'force_lang' => 1, 'hide_default' => true, 'rewrite' => true ) as $gq_key => $gq_value ) {
			if ( $gq_model->options->get( $gq_key ) !== $gq_value ) {
				$gq_check( $gq_model->options->set( $gq_key, $gq_value ), "Could not set Polylang's {$gq_key}" );
				WP_CLI::log( "Set Polylang's {$gq_key}." );
			}
		}
		$gq_model->options->save();
		break;
	case 'assign':
		$gq_nolang = $gq_model->get_objects_with_no_lang();
		if ( $gq_nolang ) {
			$gq_model->set_language_in_mass();
			WP_CLI::log(
				sprintf(
					'Assigned the default language to %d posts and %d terms that had none.',
					count( $gq_nolang['posts'] ?? array() ),
					count( $gq_nolang['terms'] ?? array() )
				)
			);
		}
		break;
	default:
		WP_CLI::error( "Unknown Polylang command {$gq_command}." );
}
PHP
}

current="$(polylang languages)"

listed() {
  case " $languages " in
    *":$1 "*) return 0 ;;
    *) return 1 ;;
  esac
}

# A language gq.ops.json no longer lists stops the deploy before any change.
unlisted=false
while read -r slug locale _order; do
  if [ -z "$slug" ] || listed "$slug"; then
    continue
  fi
  echo "gq.ops.json no longer lists Polylang's language $slug ($locale). List it again in wordpress.languages, or move or delete its content and delete it in WordPress (Languages), then deploy again." >&2
  unlisted=true
done <<<"$current"
[ "$unlisted" = false ] || exit 1

order=0
for language in $languages; do
  locale="${language%%:*}"
  slug="${language#*:}"
  existing="$(awk -v slug="$slug" '$1 == slug { print $2, $3 }' <<<"$current")"
  if [ -z "$existing" ]; then
    polylang add "$slug" "$locale" "$order"
  elif [ "$existing" != "$locale $order" ]; then
    polylang update "$slug" "$locale" "$order"
  fi
  order=$((order + 1))
done

polylang settings "$default_slug"
polylang assign
