// gq new and gq sync on generated sections: site content outside the
// AGENTS.md and .gitignore markers is never touched.
import assert from "node:assert/strict";
import { appendFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";

import { createFixtureSite } from "../support/fixture-site.mjs";
import { hash, newSite, readSite, snapshot } from "../support/generated-site.mjs";

const IGNORE_BEGIN =
  "# BEGIN gq: generated by @getquick/site; gq sync rewrites this section. Add site rules outside it.";
const IGNORE_SECTION = [
  IGNORE_BEGIN,
  ".DS_Store",
  "*.log",
  "node_modules/",
  ".pnpm-store/",
  ".env",
  ".env.local",
  ".env.*.local",
  ".dev.vars",
  ".dev.vars.*",
  ".env.keys",
  ".env.*.keys",
  ".vscode/settings.json",
  "",
  "# Local reports and generated output",
  "dist/",
  "playwright-report/",
  "test-results/",
  "coverage/",
  "",
  "# DDEV / local tooling state",
  ".ddev/.global/",
  ".ddev/.data/",
  "",
  "# vite-plus generated git-hook shims (regenerated by `pnpm install`'s prepare script)",
  ".vite-hooks/_/",
  "",
  "# Alchemy local logs/cache (state lives in the Cloudflare state store)",
  ".alchemy/",
  "",
  "# Wrangler build output and local state",
  ".wrangler/",
  "",
  "# WordPress language packs, which the CMS deploy (and gq db sync) installs",
  "apps/cms/web/app/languages/",
  "# END gq",
  "",
].join("\n");
const AGENTS_BEGIN =
  "<!-- BEGIN gq: generated by @getquick/site; gq sync rewrites this section. Add site guidance outside it. -->";
const AGENTS_END = "<!-- END gq -->";

// The site's lock, parsed.
async function readLock(root) {
  return JSON.parse(await readSite(root, "gq.lock.json"));
}

async function writeLock(root, lock) {
  await writeFile(join(root, "gq.lock.json"), `${JSON.stringify(lock, null, 2)}\n`);
}

test("gq new writes AGENTS.md and .gitignore as their generated sections, hashed in the lock", async () => {
  const site = await newSite();

  assert.equal(await readSite(site.root, ".gitignore"), IGNORE_SECTION);
  const agents = await readSite(site.root, "AGENTS.md");
  assert.ok(agents.startsWith(`${AGENTS_BEGIN}\n`), agents);
  assert.ok(agents.endsWith(`\n${AGENTS_END}\n`), agents);
  assert.match(agents, /^## Scope$/mu);
  assert.match(agents, /start a new session there/u);
  assert.match(agents, /^## Managed files$/mu);
  assert.match(agents, /^### Issue tracker$/mu);

  const lock = await readLock(site.root);
  assert.deepEqual(lock.sections, {
    ".gitignore": hash(IGNORE_SECTION),
    "AGENTS.md": hash(agents),
  });
});

test("an edit inside a generated section stops gq sync with a diff, and nothing is written", async () => {
  const site = await newSite();
  const ignore = IGNORE_SECTION.replace("coverage/\n", "coverage/\n.cache/\n");
  await writeFile(join(site.root, ".gitignore"), `/vendor\n\n${ignore}`);
  const before = await snapshot(site.root);
  const diff = [
    ".gitignore (generated section): edited since gq last wrote it (gq.lock.json); gq sync would write:",
    "--- .gitignore",
    "+++ .gitignore (gq sync)",
    "@@ -19,7 +19,6 @@",
    " playwright-report/",
    " test-results/",
    " coverage/",
    "-.cache/",
    " ",
    " # DDEV / local tooling state",
    " .ddev/.global/",
    "",
  ].join("\n");

  for (const argv of [["sync"], ["sync", "--check"]]) {
    const result = await site.run(argv);
    assert.equal(result.code, 1);
    assert.equal(result.stdout, `gq.ops.json: up to date (schema v1).\n${diff}`);
    assert.equal(
      result.stderr,
      "gq: Local edits to managed files: .gitignore. gq sync writes nothing until each is " +
        "reverted, or deleted to be regenerated.\n",
    );
    assert.deepEqual(await snapshot(site.root), before);
  }
});

// A site an older gq generated, whose AGENTS.md section the installed
// blueprint has since changed: the lock records the section gq wrote then.
async function siteWithOldAgentsSection() {
  const site = await newSite();
  const section = await readSite(site.root, "AGENTS.md");
  const old = section.replace("## Safety\n", "## Safety rules\n");
  await writeFile(join(site.root, "AGENTS.md"), old);
  const lock = await readLock(site.root);
  lock.gq = "0.11.0";
  lock.sections["AGENTS.md"] = hash(old);
  await writeLock(site.root, lock);
  return { ...site, section, old };
}

test("a template change to an unedited section is applied, keeping the site's content around it", async () => {
  const site = await siteWithOldAgentsSection();
  const above = "# Acme workspace guidance\n\nAcme is a content site.\n\n";
  const below = "\n## Acme plugins\n\n- `acme-blocks` owns the blocks.\n";
  await writeFile(join(site.root, "AGENTS.md"), `${above}${site.old}${below}`);
  const ignoreBelow = "\n# Acme\n/apps/cms/web/app/uploads/\n";
  await appendFile(join(site.root, ".gitignore"), ignoreBelow);
  const before = await snapshot(site.root);

  const check = await site.run(["sync", "--check"]);
  assert.equal(check.code, 1);
  assert.equal(
    check.stdout,
    [
      "gq.ops.json: up to date (schema v1).",
      "AGENTS.md: pending, gq sync would update its generated section.",
      "gq.lock.json: pending, gq sync would update it.",
      "",
    ].join("\n"),
  );
  assert.deepEqual(await snapshot(site.root), before);

  const sync = await site.run(["sync"]);
  assert.equal(sync.code, 0, sync.stderr);
  assert.equal(
    sync.stdout,
    [
      "gq.ops.json: up to date (schema v1).",
      "AGENTS.md: updated (generated section).",
      "gq.lock.json: updated.",
      "",
    ].join("\n"),
  );
  assert.equal(await readSite(site.root, "AGENTS.md"), `${above}${site.section}${below}`);
  assert.equal(await readSite(site.root, ".gitignore"), `${IGNORE_SECTION}${ignoreBelow}`);
  assert.equal((await readLock(site.root)).sections["AGENTS.md"], hash(site.section));

  const again = await site.run(["sync", "--check"]);
  assert.equal(again.code, 0, again.stdout);
  for (const { fetch, exec } of [check, sync]) {
    assert.deepEqual(fetch.requests, []);
    assert.deepEqual(exec.calls, []);
  }
});

test("gq sync appends a generated section to a file that has none, keeping the file's content", async () => {
  const site = await createFixtureSite({
    ops: { schemaVersion: 1, project: "acme", variant: "content" },
    files: { ".gitignore": "/vendor\n.cache/" },
  });

  const result = await site.run(["sync"]);

  assert.equal(result.code, 0, result.stderr);
  assert.match(result.stdout, /^\.gitignore: updated \(generated section\)\.$/mu);
  assert.equal(await readSite(site.root, ".gitignore"), `/vendor\n.cache/\n\n${IGNORE_SECTION}`);
  assert.equal((await site.run(["sync", "--check"])).code, 0);
});

test("gq sync refuses a generated section whose markers it can't pair", async () => {
  const site = await newSite();
  const ignore = await readSite(site.root, ".gitignore");
  await writeFile(join(site.root, ".gitignore"), ignore.replace("# END gq\n", ""));
  const before = await snapshot(site.root);

  const result = await site.run(["sync", "--check"]);

  assert.equal(result.code, 1);
  assert.equal(
    result.stderr,
    `gq: .gitignore must hold gq's generated section once, from a "# BEGIN gq…" line to a ` +
      '"# END gq" line. Restore the markers, or remove both and gq sync appends the section.\n',
  );
  assert.deepEqual(await snapshot(site.root), before);
});
